#!/usr/bin/env node

import { createInterface } from "node:readline";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, normalize } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn } from "node:child_process";
import { gunzipSync } from "node:zlib";
import { runSequentialSnippetPair } from "./snippet-pair.mjs";

// MCP stdio reserves stdout exclusively for JSON-RPC. Keep every incidental
// message off that channel and write protocol messages explicitly below.
const protocolWrite = process.stdout.write.bind(process.stdout);
process.stdout.write = () => true;
for (const level of ["log", "info", "warn", "debug", "error"]) {
  console[level] = () => {};
}

const ALLOWED_REPOS = new Set(
  (process.env.REPO_RESCUE_ALLOWED_REPOS || "pallets/click")
    .split(",")
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean),
);

const configuredNodeToolset = String(
  process.env.REPO_RESCUE_NODE_TOOLSET === undefined
    ? "full"
    : process.env.REPO_RESCUE_NODE_TOOLSET,
)
  .trim()
  .toLowerCase();
// A typo in a hosted deployment must not accidentally expose the broader
// compatibility tool surface. Unset keeps the backwards-compatible full set;
// every unrecognised explicit value fails closed to the snippet-only set.
const NODE_TOOLSET = configuredNodeToolset === "full" ? "full" : "snippet";

const MAX_SNIPPET_CHARS = 12_000;
const MAX_SNIPPET_CASES = 4;
const MAX_SNIPPET_STDOUT_CHARS = 6_000;
const MAX_SNIPPET_STDERR_CHARS = 3_000;
const MAX_REPORTED_ERROR_CHARS = 2_000;
const MAX_CASE_NAME_CHARS = 200;
const MAX_CASE_STDIN_CHARS = 12_000;
const MAX_CASE_EXPECTED_STDOUT_CHARS = 12_000;
const MAX_REPO_URL_CHARS = 500;
const MAX_WORKER_PROTOCOL_BYTES = 1024 * 1024;
const MAX_WORKER_STDERR_BYTES = 32 * 1024;
const SNIPPET_WORKER_PATH = fileURLToPath(new URL("./snippet-worker.mjs", import.meta.url));
const configuredWorkerTimeout = Number.parseInt(process.env.REPO_RESCUE_SNIPPET_WORKER_TIMEOUT_MS || "6000", 10);
const SNIPPET_WORKER_TIMEOUT_MS = Number.isFinite(configuredWorkerTimeout)
  ? Math.min(15_000, Math.max(500, configuredWorkerTimeout))
  : 6_000;

// Profiles are used only for read-only repository inspection in this Node
// launcher. Repository execution is exclusively owned by the Python MCP
// backend, where Docker isolation and the full verifier are available.
const REPOSITORY_PROFILES = new Map([
  [
    "pallets/click",
    {
      id: "pallets-click-core-v1",
      language: "python",
    },
  ],
]);
let snippetQueue = Promise.resolve();

function withSnippetLock(task) {
  const run = snippetQueue.then(task, task);
  snippetQueue = run.catch(() => {});
  return run;
}

const tools = [
  {
    name: "rescue_python_snippet",
    description: "Actually run a student's original and AI-repaired Python snippet in separate disposable WebAssembly child processes. Use after generating a minimal fix so the answer can show before/after evidence instead of an unverified suggestion.",
    inputSchema: {
      type: "object",
      properties: {
        original_code: { type: "string", maxLength: MAX_SNIPPET_CHARS, description: "The user's original Python code" },
        candidate_code: { type: "string", maxLength: MAX_SNIPPET_CHARS, description: "The minimally repaired Python code generated by the agent" },
        reported_error: { type: "string", maxLength: MAX_REPORTED_ERROR_CHARS, description: "Optional error text supplied by the user" },
        test_cases: {
          type: "array",
          maxItems: MAX_SNIPPET_CASES,
          description: "Optional stdin/output examples. Omit expected_stdout when only a successful run is required.",
          items: {
            type: "object",
            properties: {
              name: { type: "string", maxLength: MAX_CASE_NAME_CHARS },
              stdin: { type: "string", maxLength: MAX_CASE_STDIN_CHARS },
              expected_stdout: { type: "string", maxLength: MAX_CASE_EXPECTED_STDOUT_CHARS },
            },
            additionalProperties: false,
          },
        },
      },
      required: ["original_code", "candidate_code"],
      additionalProperties: false,
    },
  },
  {
    name: "inspect_github_project",
    description: "Inspect a profiled, allow-listed public GitHub repository and return its exact commit and project evidence. Repositories without an explicit verification profile return unsupported.",
    inputSchema: {
      type: "object",
      properties: { repo_url: { type: "string", maxLength: MAX_REPO_URL_CHARS, description: "Public GitHub repository URL" } },
      required: ["repo_url"],
      additionalProperties: false,
    },
  },
  {
    name: "reproduce_python_project",
    description: "Compatibility endpoint that refuses Node-side repository execution and directs callers to the Python MCP Docker backend.",
    inputSchema: {
      type: "object",
      properties: { repo_url: { type: "string", maxLength: MAX_REPO_URL_CHARS, description: "Public GitHub repository URL" } },
      required: ["repo_url"],
      additionalProperties: false,
    },
  },
  {
    name: "windows_environment_probe",
    description: "Return a non-mutating PowerShell probe the user can run locally; never claims automatic computer access.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
];
const exposedTools = NODE_TOOLSET === "snippet"
  ? tools.filter((tool) => tool.name === "rescue_python_snippet")
  : tools;
const exposedToolNames = new Set(exposedTools.map((tool) => tool.name));
const knownToolNames = new Set(tools.map((tool) => tool.name));

function parseRepo(url) {
  const match = /^https:\/\/github\.com\/([^/]+)\/([^/#?]+?)(?:\.git)?\/?$/i.exec(String(url || "").trim());
  if (!match) throw new Error("Only canonical public https://github.com/owner/repository URLs are accepted.");
  const slug = `${match[1]}/${match[2]}`.toLowerCase();
  if (!ALLOWED_REPOS.has(slug)) throw new Error(`Execution is restricted to the allow-list: ${[...ALLOWED_REPOS].join(", ")}`);
  return { slug, url: `https://github.com/${slug}.git` };
}

function unsupportedRepositoryProfile(repo, sourceUrl) {
  return {
    ok: false,
    status: "unsupported_repository_profile",
    supported: false,
    verified: false,
    executed: false,
    repository: repo.slug,
    source_url: String(sourceUrl || ""),
    commit_sha: null,
    detected_language: "unknown",
    repository_profile: null,
    backend: null,
    verification_command: null,
    exit_code: null,
    counts: null,
    supported_profiles: [...REPOSITORY_PROFILES.keys()],
    error: `No explicit verification profile is configured for ${repo.slug}; no repository code was downloaded or executed.`,
  };
}

function extractTarGz(bytes, destination) {
  const tar = gunzipSync(bytes);
  let offset = 0;
  while (offset + 512 <= tar.length) {
    const header = tar.subarray(offset, offset + 512);
    if (header.every((byte) => byte === 0)) break;
    const readString = (start, length) => header.subarray(start, start + length).toString("utf8").replace(/\0.*$/s, "");
    const name = readString(0, 100);
    const prefix = readString(345, 155);
    const size = Number.parseInt(readString(124, 12).trim() || "0", 8);
    const type = String.fromCharCode(header[156] || 48);
    const archivePath = prefix ? `${prefix}/${name}` : name;
    const relative = archivePath.split("/").slice(1).join("/");
    if (relative && !relative.split("/").includes("..") && !relative.startsWith("/")) {
      const target = normalize(join(destination, relative));
      if (target.startsWith(normalize(destination + "/")) || target === normalize(destination)) {
        if (type === "5") {
          mkdirSync(target, { recursive: true });
        } else if (type === "0" || type === "\0") {
          mkdirSync(dirname(target), { recursive: true });
          writeFileSync(target, tar.subarray(offset + 512, offset + 512 + size));
        }
      }
    }
    offset += 512 + Math.ceil(size / 512) * 512;
  }
}

async function cloneRepository(repoUrl, parsedRepo = null) {
  const repo = parsedRepo || parseRepo(repoUrl);
  const root = mkdtempSync(join(tmpdir(), "repo-rescue-node-"));
  const project = join(root, "project");
  mkdirSync(project, { recursive: true });
  try {
    const headers = { "User-Agent": "repo-rescue-mcp", Accept: "application/vnd.github+json" };
    const commitResponse = await fetch(`https://api.github.com/repos/${repo.slug}/commits/HEAD`, { headers });
    if (!commitResponse.ok) throw new Error(`GitHub commit lookup failed with HTTP ${commitResponse.status}.`);
    const commit = String((await commitResponse.json()).sha || "");
    if (!/^[0-9a-f]{40}$/i.test(commit)) throw new Error("GitHub did not return a valid 40-character commit SHA.");
    const archiveResponse = await fetch(`https://codeload.github.com/${repo.slug}/tar.gz/${commit}`, { headers });
    if (!archiveResponse.ok) throw new Error(`GitHub archive download failed with HTTP ${archiveResponse.status}.`);
    extractTarGz(Buffer.from(await archiveResponse.arrayBuffer()), project);
    return { ...repo, root, project, commit };
  } catch (error) {
    rmSync(root, { recursive: true, force: true });
    throw error;
  }
}

async function inspectProject(repoUrl) {
  const repo = parseRepo(repoUrl);
  const profile = REPOSITORY_PROFILES.get(repo.slug);
  if (!profile) return unsupportedRepositoryProfile(repo, repoUrl);
  const snapshot = await cloneRepository(repoUrl, repo);
  try {
    let pyproject = "";
    try { pyproject = readFileSync(join(snapshot.project, "pyproject.toml"), "utf8"); } catch {}
    const requiresPython = /requires-python\s*=\s*["']([^"']+)/.exec(pyproject)?.[1] || "not declared";
    return {
      ok: true,
      verified: false,
      repository: snapshot.slug,
      source_url: repoUrl,
      commit_sha: snapshot.commit,
      status: "inspected",
      supported: true,
      executed: false,
      detected_language: profile.language,
      repository_profile: profile.id,
      requires_python: requiresPython,
      evidence_note: "Commit and project metadata were read from a fresh shallow clone; no test result is claimed by this inspection tool.",
    };
  } finally {
    rmSync(snapshot.root, { recursive: true, force: true });
  }
}

function normalizeOutput(text) {
  return String(text ?? "").replace(/\r\n/g, "\n").trimEnd();
}

function boundedSnippetExecution(result) {
  const stdout = String(result?.stdout ?? "");
  const stderr = String(result?.stderr ?? "");
  const stdoutChars = Number.isFinite(result?.stdout_chars) ? result.stdout_chars : stdout.length;
  const stderrChars = Number.isFinite(result?.stderr_chars) ? result.stderr_chars : stderr.length;
  return {
    ...result,
    stdout: stdout.slice(-MAX_SNIPPET_STDOUT_CHARS),
    stderr: stderr.slice(-MAX_SNIPPET_STDERR_CHARS),
    stdout_chars: stdoutChars,
    stderr_chars: stderrChars,
    stdout_truncated: result?.stdout_complete === false || stdoutChars > MAX_SNIPPET_STDOUT_CHARS,
    stderr_truncated: result?.stderr_complete === false || stderrChars > MAX_SNIPPET_STDERR_CHARS,
  };
}

function validateSnippetInput(code, field) {
  if (typeof code !== "string" || !code.trim()) throw new Error(`${field} must contain Python code.`);
  if (code.length > MAX_SNIPPET_CHARS) throw new Error(`${field} exceeds the ${MAX_SNIPPET_CHARS}-character limit.`);
}

function invalidSnippetRequest(message, submitted = 0) {
  return {
    ok: false,
    mode: "single_snippet_rescue",
    verification_level: "L1_SNIPPET_EXECUTION",
    status: "invalid_request",
    fix_verified: false,
    candidate_passed: false,
    before_failed: false,
    case_counts: { submitted, executed: 0, maximum: MAX_SNIPPET_CASES },
    error: `${message} No code was executed.`,
    test_results: [],
  };
}

function validateSnippetMetadata(args) {
  if (args.reported_error !== undefined) {
    if (typeof args.reported_error !== "string") return "reported_error must be a string.";
    if (args.reported_error.length > MAX_REPORTED_ERROR_CHARS) {
      return `reported_error exceeds the ${MAX_REPORTED_ERROR_CHARS}-character limit.`;
    }
  }
  if (args.test_cases !== undefined && !Array.isArray(args.test_cases)) {
    return "test_cases must be an array.";
  }
  for (const [index, test] of (args.test_cases || []).entries()) {
    if (!test || typeof test !== "object" || Array.isArray(test)) {
      return `test_cases[${index}] must be an object.`;
    }
    for (const [field, maximum] of [
      ["name", MAX_CASE_NAME_CHARS],
      ["stdin", MAX_CASE_STDIN_CHARS],
      ["expected_stdout", MAX_CASE_EXPECTED_STDOUT_CHARS],
    ]) {
      if (test[field] !== undefined && typeof test[field] !== "string") {
        return `test_cases[${index}].${field} must be a string.`;
      }
      if (typeof test[field] === "string" && test[field].length > maximum) {
        return `test_cases[${index}].${field} exceeds the ${maximum}-character limit.`;
      }
    }
  }
  return null;
}

function workerFailure(errorType, message) {
  const bounded = String(message || errorType).slice(-MAX_SNIPPET_STDERR_CHARS);
  return {
    ok: false,
    stdout: "",
    stderr: bounded,
    stdout_chars: 0,
    stderr_chars: bounded.length,
    stdout_complete: true,
    stderr_complete: true,
    error_type: errorType,
    error_message: bounded.split("\n").at(-1) || bounded,
  };
}

function runSnippetWorker(code, cases) {
  return new Promise((resolve) => {
    const child = spawn(
      process.execPath,
      ["--max-old-space-size=192", SNIPPET_WORKER_PATH],
      { stdio: ["pipe", "pipe", "pipe"], windowsHide: true },
    );
    const stdoutChunks = [];
    const stderrChunks = [];
    let stdoutBytes = 0;
    let stderrBytes = 0;
    let failure = null;
    let timedOut = false;
    let settled = false;

    const terminate = () => {
      if (!child.killed) child.kill("SIGKILL");
    };
    const timer = setTimeout(() => {
      timedOut = true;
      terminate();
    }, SNIPPET_WORKER_TIMEOUT_MS);

    child.stdout.on("data", (chunk) => {
      stdoutBytes += chunk.length;
      if (stdoutBytes > MAX_WORKER_PROTOCOL_BYTES) {
        failure = {
          type: "WorkerProtocolError",
          message: `Snippet worker exceeded the ${MAX_WORKER_PROTOCOL_BYTES}-byte protocol limit.`,
        };
        terminate();
        return;
      }
      stdoutChunks.push(chunk);
    });
    child.stderr.on("data", (chunk) => {
      stderrBytes += chunk.length;
      stderrChunks.push(chunk);
      while (stderrBytes > MAX_WORKER_STDERR_BYTES && stderrChunks.length > 1) {
        stderrBytes -= stderrChunks.shift().length;
      }
      if (stderrBytes > MAX_WORKER_STDERR_BYTES && stderrChunks.length === 1) {
        stderrChunks[0] = stderrChunks[0].subarray(-MAX_WORKER_STDERR_BYTES);
        stderrBytes = stderrChunks[0].length;
      }
    });
    child.on("error", (error) => {
      failure = { type: "WorkerLaunchError", message: String(error?.message || error) };
    });
    child.on("close", (exitCode) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (timedOut) {
        resolve({
          ok: false,
          error_type: "WorkerTimeoutError",
          error: `Snippet worker exceeded the ${SNIPPET_WORKER_TIMEOUT_MS} ms wall-clock limit.`,
        });
        return;
      }
      if (failure) {
        resolve({ ok: false, error_type: failure.type, error: failure.message });
        return;
      }
      const output = Buffer.concat(stdoutChunks).toString("utf8").trim();
      try {
        const value = JSON.parse(output);
        if (!value?.ok || !Array.isArray(value.results) || value.results.length !== cases.length) {
          const workerError = value?.error || Buffer.concat(stderrChunks).toString("utf8") || `worker exited ${exitCode}`;
          resolve({ ok: false, error_type: value?.error_type || "WorkerProtocolError", error: workerError });
          return;
        }
        resolve(value);
      } catch {
        resolve({
          ok: false,
          error_type: "WorkerProtocolError",
          error: `Snippet worker returned invalid bounded protocol output (exit ${exitCode}).`,
        });
      }
    });
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify({ code, cases: cases.map((item) => ({ stdin: String(item?.stdin ?? "") })) }));
  });
}

async function rescuePythonSnippet(args) {
  validateSnippetInput(args.original_code, "original_code");
  validateSnippetInput(args.candidate_code, "candidate_code");
  const submittedCaseCount = Array.isArray(args.test_cases) ? args.test_cases.length : 0;
  if (submittedCaseCount > MAX_SNIPPET_CASES) {
    return invalidSnippetRequest(
      `test_cases contains ${submittedCaseCount} items; the maximum is ${MAX_SNIPPET_CASES}.`,
      submittedCaseCount,
    );
  }
  const metadataError = validateSnippetMetadata(args);
  if (metadataError) return invalidSnippetRequest(metadataError, submittedCaseCount);
  return withSnippetLock(async () => {
    const cases = Array.isArray(args.test_cases) && args.test_cases.length
      ? args.test_cases
      : [{ name: "default", stdin: "" }];
    // Original and candidate never share an interpreter. Run their two fresh
    // Pyodide child processes sequentially so low-memory hosts never keep both
    // runtimes resident at once. Each child retains its own heap, protocol,
    // output, and wall-clock limits; the parent owns the trusted verdict.
    const { beforeBatch, afterBatch } = await runSequentialSnippetPair(
      runSnippetWorker,
      args.original_code,
      args.candidate_code,
      cases,
    );
    const results = [];
    for (let index = 0; index < cases.length; index += 1) {
      const test = cases[index] || {};
      const before = beforeBatch.ok
        ? beforeBatch.results[index]
        : workerFailure(beforeBatch.error_type || "WorkerRuntimeError", beforeBatch.error);
      const after = afterBatch.ok
        ? afterBatch.results[index]
        : workerFailure(afterBatch.error_type || "WorkerRuntimeError", afterBatch.error);
      const expectedProvided = Object.prototype.hasOwnProperty.call(test, "expected_stdout");
      const outputMatches = !expectedProvided
        || (after.stdout_complete !== false && normalizeOutput(after.stdout) === normalizeOutput(test.expected_stdout));
      const originalOutputMatches = !expectedProvided
        || (before.stdout_complete !== false && normalizeOutput(before.stdout) === normalizeOutput(test.expected_stdout));
      const originalFailed = !before.ok || !originalOutputMatches;
      results.push({
        name: String(test.name || `case-${index + 1}`),
        expected_stdout: expectedProvided ? String(test.expected_stdout) : null,
        before: boundedSnippetExecution(before),
        after: boundedSnippetExecution(after),
        original_failed: originalFailed,
        original_output_matches: originalOutputMatches,
        candidate_passed: after.ok && outputMatches,
        output_matches: outputMatches,
      });
    }
    const beforeFailed = results.some((item) => item.original_failed);
    const candidatePassed = results.every((item) => item.candidate_passed);
    const oracleBacked = results.every((item) => item.expected_stdout !== null);
    const sourceChanged = args.original_code !== args.candidate_code;
    const runtimeRepairObserved = sourceChanged && beforeFailed && candidatePassed;
    const fixVerified = oracleBacked && runtimeRepairObserved;
    return {
      ok: true,
      mode: "single_snippet_rescue",
      verification_level: "L1_SNIPPET_EXECUTION",
      execution_backend: "pyodide_disposable_child_process",
      worker_execution_strategy: "sequential_fresh_children",
      worker_timeout_ms: SNIPPET_WORKER_TIMEOUT_MS,
      status: fixVerified ? "fix_verified" : candidatePassed ? "candidate_runs" : "candidate_failed",
      fix_verified: fixVerified,
      candidate_passed: candidatePassed,
      before_failed: beforeFailed,
      source_changed: sourceChanged,
      oracle_backed: oracleBacked,
      runtime_repair_observed: runtimeRepairObserved,
      case_counts: {
        submitted: submittedCaseCount,
        executed: results.length,
        maximum: MAX_SNIPPET_CASES,
      },
      reported_error: args.reported_error || null,
      test_results: results,
      user_summary: fixVerified
        ? `修复已真实运行验证：修改前失败，修改后通过 ${results.length} 个用例。`
        : candidatePassed
          ? runtimeRepairObserved && !oracleBacked
            ? `候选代码不再报错，但用例缺少预期输出，只能证明运行恢复，不能宣称正确修复。`
            : `候选代码通过 ${results.length} 个运行用例，但未观察到可验证的源码修复，不能宣称已验证修复。`
          : `候选代码仍未通过全部运行用例，请根据错误继续修改。`,
      boundary: "This verifies the supplied snippet and test cases only; it is not a full-project or paper reproduction claim.",
    };
  });
}

async function reproduceProject(repoUrl) {
  const repo = parseRepo(repoUrl);
  const profile = REPOSITORY_PROFILES.get(repo.slug);
  return {
    ok: false,
    status: "repository_execution_disabled",
    supported: false,
    verified: false,
    executed: false,
    repository: repo.slug,
    source_url: String(repoUrl || ""),
    commit_sha: null,
    detected_language: profile?.language || "unknown",
    repository_profile: profile?.id || null,
    backend: null,
    verification_command: null,
    exit_code: null,
    counts: null,
    error: "The Node stdio launcher never clones or executes repository code. Use the Python RepoRescue MCP backend with Docker isolation for repository reproduction, repair, and verification.",
    next_step: "Start the Python MCP server and call start_prepare_github_repair, poll get_repair_job, then call start_verify_github_patch and poll the new job with Docker enabled.",
  };
}

function windowsProbe() {
  return {
    ok: true,
    platform: "windows",
    changes_system: false,
    command: "$ErrorActionPreference='Continue'; Write-Output '=== SYSTEM ==='; Get-CimInstance Win32_OperatingSystem | Select-Object Caption,Version,OSArchitecture; Write-Output '=== PYTHON ==='; python --version; Write-Output '=== PIP ==='; python -m pip --version; Write-Output '=== PACKAGES ==='; python -m pip list --format=freeze",
    instructions: "Run this in PowerShell, review it, and paste only the relevant output back. RepoRescue cannot read a user's computer automatically.",
  };
}

async function callTool(name, args) {
  if (!exposedToolNames.has(name)) {
    if (knownToolNames.has(name)) {
      const error = new Error(
        `Tool "${name}" is disabled by REPO_RESCUE_NODE_TOOLSET=${NODE_TOOLSET}.`,
      );
      error.code = "tool_unavailable";
      throw error;
    }
    throw new Error(`Unknown tool: ${name}`);
  }
  if (name === "rescue_python_snippet") return rescuePythonSnippet(args);
  if (name === "inspect_github_project") return inspectProject(args.repo_url);
  if (name === "reproduce_python_project") return reproduceProject(args.repo_url);
  if (name === "windows_environment_probe") return windowsProbe();
  throw new Error(`Unknown tool: ${name}`);
}

function send(message) {
  const payload = `${JSON.stringify(message)}\n`;
  protocolWrite(payload);
}

const input = createInterface({ input: process.stdin, crlfDelay: Infinity });
input.on("line", async (line) => {
  if (!line.trim()) return;
  let request;
  try { request = JSON.parse(line); } catch { return; }
  if (request.id === undefined || request.id === null) return;
  try {
    let result;
    if (request.method === "initialize") {
      result = { protocolVersion: request.params?.protocolVersion || "2025-03-26", capabilities: { tools: { listChanged: false } }, serverInfo: { name: "repo-rescue-mcp", version: "0.4.0" } };
    } else if (request.method === "ping") {
      result = {};
    } else if (request.method === "tools/list") {
      result = { tools: exposedTools };
    } else if (request.method === "tools/call") {
      const value = await callTool(request.params?.name, request.params?.arguments || {});
      result = { content: [{ type: "text", text: JSON.stringify(value, null, 2) }], isError: false };
    } else {
      send({ jsonrpc: "2.0", id: request.id, error: { code: -32601, message: `Method not found: ${request.method}` } });
      return;
    }
    send({ jsonrpc: "2.0", id: request.id, result });
  } catch (error) {
    send({ jsonrpc: "2.0", id: request.id, result: { content: [{ type: "text", text: JSON.stringify({ ok: false, verified: false, status: error?.code || "tool_call_failed", error: String(error?.message || error) }) }], isError: true } });
  }
});
