#!/usr/bin/env node

import { createInterface } from "node:readline";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, normalize } from "node:path";
import { spawnSync } from "node:child_process";
import { gunzipSync } from "node:zlib";
import { createHash } from "node:crypto";

// MCP stdio reserves stdout exclusively for JSON-RPC. Third-party runtimes
// (notably Pyodide package loading) may log through console, so keep every
// incidental message on stderr and write protocol messages explicitly below.
const protocolWrite = process.stdout.write.bind(process.stdout);
process.stdout.write = () => true;
for (const level of ["log", "info", "warn", "debug", "error"]) {
  console[level] = () => {};
}

const ALLOWED_REPOS = new Set(
  (process.env.REPO_RESCUE_ALLOWED_REPOS || "pallets/click")
    .split(",")
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean),
);

const SERVER_BUILD = "repo-rescue-verified-code-20260723-v3";
const ATTESTATION_SALT = "RR::portable-evidence::v1::9d2c71";
const MAX_SNIPPET_CHARS = 12_000;
const MAX_SNIPPET_CASES = 4;

function withAttestation(result) {
  const payload = [
    SERVER_BUILD,
    result.commit_sha ?? "null",
    result.backend ?? "null",
    result.verification_command ?? "null",
    String(result.exit_code ?? "null"),
    String(result.counts?.passed ?? 0),
    String(result.duration_seconds ?? "null"),
  ].join("|");
  return {
    ...result,
    server_build: SERVER_BUILD,
    attestation_payload: payload,
    attestation_sha256: createHash("sha256").update(`${ATTESTATION_SALT}|${payload}`).digest("hex"),
  };
}

const pyodideLog = [];
let pyodideRuntimePromise;
let pytestRuntimePromise;
let pyodideQueue = Promise.resolve();

function withPyodideLock(task) {
  const run = pyodideQueue.then(task, task);
  pyodideQueue = run.catch(() => {});
  return run;
}

function getPyodideRuntime() {
  pyodideRuntimePromise ||= import("pyodide")
    .then(async ({ loadPyodide }) => {
      return loadPyodide({
        stdout: (text) => pyodideLog.push(String(text)),
        stderr: (text) => pyodideLog.push(String(text)),
      });
    })
    .catch((error) => ({ startupError: String(error?.message || error) }));
  return pyodideRuntimePromise;
}

function ensurePytestRuntime(runtime) {
  pytestRuntimePromise ||= runtime.loadPackage("pytest", {
        messageCallback: (text) => pyodideLog.push(String(text)),
        errorCallback: (text) => pyodideLog.push(String(text)),
    })
    .then(() => runtime)
    .catch((error) => ({ startupError: String(error?.message || error) }));
  return pytestRuntimePromise;
}

const tools = [
  {
    name: "rescue_python_snippet",
    description: "Actually run a student's original and AI-repaired Python snippet in a constrained WebAssembly runtime. Use after generating a minimal fix so the answer can show before/after evidence instead of an unverified suggestion.",
    inputSchema: {
      type: "object",
      properties: {
        original_code: { type: "string", description: "The user's original Python code" },
        candidate_code: { type: "string", description: "The minimally repaired Python code generated by the agent" },
        reported_error: { type: "string", description: "Optional error text supplied by the user" },
        test_cases: {
          type: "array",
          maxItems: MAX_SNIPPET_CASES,
          description: "Optional stdin/output examples. Omit expected_stdout when only a successful run is required.",
          items: {
            type: "object",
            properties: {
              name: { type: "string" },
              stdin: { type: "string" },
              expected_stdout: { type: "string" },
            },
            additionalProperties: false,
          },
        },
      },
      required: ["original_code", "candidate_code"],
      additionalProperties: false,
    },
  },
  {
    name: "inspect_github_project",
    description: "Inspect an allow-listed public GitHub repository and return its exact commit and Python project evidence.",
    inputSchema: {
      type: "object",
      properties: { repo_url: { type: "string", description: "Public GitHub repository URL" } },
      required: ["repo_url"],
      additionalProperties: false,
    },
  },
  {
    name: "reproduce_python_project",
    description: "Clone and actually run the allow-listed Python repository tests, returning exit code, counts, command and logs.",
    inputSchema: {
      type: "object",
      properties: { repo_url: { type: "string", description: "Public GitHub repository URL" } },
      required: ["repo_url"],
      additionalProperties: false,
    },
  },
  {
    name: "windows_environment_probe",
    description: "Return a non-mutating PowerShell probe the user can run locally; never claims automatic computer access.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
];

function parseRepo(url) {
  const match = /^https:\/\/github\.com\/([^/]+)\/([^/#?]+?)(?:\.git)?\/?$/i.exec(String(url || "").trim());
  if (!match) throw new Error("Only canonical public https://github.com/owner/repository URLs are accepted.");
  const slug = `${match[1]}/${match[2]}`.toLowerCase();
  if (!ALLOWED_REPOS.has(slug)) throw new Error(`Execution is restricted to the allow-list: ${[...ALLOWED_REPOS].join(", ")}`);
  return { slug, url: `https://github.com/${slug}.git` };
}

function run(command, args, options = {}) {
  const started = Date.now();
  const result = spawnSync(command, args, {
    cwd: options.cwd,
    env: options.env || process.env,
    encoding: "utf8",
    timeout: options.timeout || 60000,
    maxBuffer: 12 * 1024 * 1024,
  });
  return {
    command: [command, ...args].join(" "),
    exit_code: result.status,
    timed_out: result.error?.code === "ETIMEDOUT",
    duration_seconds: Math.round((Date.now() - started) / 100) / 10,
    stdout: String(result.stdout || "").slice(-12000),
    stderr: String(result.stderr || result.error?.message || "").slice(-12000),
  };
}

function extractTarGz(bytes, destination) {
  const tar = gunzipSync(bytes);
  let offset = 0;
  while (offset + 512 <= tar.length) {
    const header = tar.subarray(offset, offset + 512);
    if (header.every((byte) => byte === 0)) break;
    const readString = (start, length) => header.subarray(start, start + length).toString("utf8").replace(/\0.*$/s, "");
    const name = readString(0, 100);
    const prefix = readString(345, 155);
    const size = Number.parseInt(readString(124, 12).trim() || "0", 8);
    const type = String.fromCharCode(header[156] || 48);
    const archivePath = prefix ? `${prefix}/${name}` : name;
    const relative = archivePath.split("/").slice(1).join("/");
    if (relative && !relative.split("/").includes("..") && !relative.startsWith("/")) {
      const target = normalize(join(destination, relative));
      if (target.startsWith(normalize(destination + "/")) || target === normalize(destination)) {
        if (type === "5") {
          mkdirSync(target, { recursive: true });
        } else if (type === "0" || type === "\0") {
          mkdirSync(dirname(target), { recursive: true });
          writeFileSync(target, tar.subarray(offset + 512, offset + 512 + size));
        }
      }
    }
    offset += 512 + Math.ceil(size / 512) * 512;
  }
}

async function cloneRepository(repoUrl) {
  const repo = parseRepo(repoUrl);
  const root = mkdtempSync(join(tmpdir(), "repo-rescue-node-"));
  const project = join(root, "project");
  mkdirSync(project, { recursive: true });
  try {
    const headers = { "User-Agent": "repo-rescue-mcp", Accept: "application/vnd.github+json" };
    const commitResponse = await fetch(`https://api.github.com/repos/${repo.slug}/commits/HEAD`, { headers });
    if (!commitResponse.ok) throw new Error(`GitHub commit lookup failed with HTTP ${commitResponse.status}.`);
    const commit = String((await commitResponse.json()).sha || "");
    if (!/^[0-9a-f]{40}$/i.test(commit)) throw new Error("GitHub did not return a valid 40-character commit SHA.");
    const archiveResponse = await fetch(`https://codeload.github.com/${repo.slug}/tar.gz/${commit}`, { headers });
    if (!archiveResponse.ok) throw new Error(`GitHub archive download failed with HTTP ${archiveResponse.status}.`);
    extractTarGz(Buffer.from(await archiveResponse.arrayBuffer()), project);
    return { ...repo, root, project, commit };
  } catch (error) {
    rmSync(root, { recursive: true, force: true });
    throw error;
  }
}

async function inspectProject(repoUrl) {
  const snapshot = await cloneRepository(repoUrl);
  try {
    let pyproject = "";
    try { pyproject = readFileSync(join(snapshot.project, "pyproject.toml"), "utf8"); } catch {}
    const requiresPython = /requires-python\s*=\s*["']([^"']+)/.exec(pyproject)?.[1] || "not declared";
    return {
      ok: true,
      verified: false,
      repository: snapshot.slug,
      source_url: repoUrl,
      commit_sha: snapshot.commit,
      detected_language: "python",
      requires_python: requiresPython,
      evidence_note: "Commit and project metadata were read from a fresh shallow clone; no test result is claimed by this inspection tool.",
    };
  } finally {
    rmSync(snapshot.root, { recursive: true, force: true });
  }
}

function extractCounts(text) {
  const counts = { passed: 0, failed: 0, skipped: 0, xfailed: 0, errors: 0 };
  for (const key of Object.keys(counts)) {
    const matches = [...String(text).matchAll(new RegExp(`(\\d+) ${key}`, "g"))];
    if (matches.length) counts[key] = Number(matches.at(-1)[1]);
  }
  return counts;
}

function normalizeOutput(text) {
  return String(text ?? "").replace(/\r\n/g, "\n").trimEnd();
}

function validateSnippetInput(code, field) {
  if (typeof code !== "string" || !code.trim()) throw new Error(`${field} must contain Python code.`);
  if (code.length > MAX_SNIPPET_CHARS) throw new Error(`${field} exceeds the ${MAX_SNIPPET_CHARS}-character limit.`);
}

async function executePythonSnippet(runtime, code, stdinText) {
  runtime.globals.set("_rr_code", code);
  runtime.globals.set("_rr_stdin", String(stdinText ?? ""));
  try {
    const raw = await runtime.runPythonAsync(`
import ast, builtins, io, json, sys, traceback

_rr_allowed_imports = {
    'math', 'statistics', 'random', 're', 'json', 'collections', 'itertools',
    'functools', 'decimal', 'fractions', 'datetime', 'string', 'heapq', 'bisect'
}
_rr_forbidden_names = {
    'open', 'exec', 'eval', 'compile', '__import__', 'breakpoint', 'globals',
    'locals', 'vars', 'getattr', 'setattr', 'delattr', 'memoryview'
}

def _rr_validate(tree):
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            names = [alias.name.split('.')[0] for alias in node.names] if isinstance(node, ast.Import) else [(node.module or '').split('.')[0]]
            if any(name not in _rr_allowed_imports for name in names):
                raise PermissionError('Only safe standard-library imports are available in quick rescue mode.')
        if isinstance(node, ast.Name) and node.id in _rr_forbidden_names:
            raise PermissionError(f'Unsafe operation is not allowed: {node.id}')
        if isinstance(node, ast.Attribute) and node.attr.startswith('__'):
            raise PermissionError('Dunder attribute access is not allowed in quick rescue mode.')

_rr_tree = ast.parse(_rr_code, filename='<student-code>')
_rr_validate(_rr_tree)
_rr_real_import = builtins.__import__
def _rr_import(name, globals=None, locals=None, fromlist=(), level=0):
    if name.split('.')[0] not in _rr_allowed_imports:
        raise PermissionError(f'Import is not allowed in quick rescue mode: {name}')
    return _rr_real_import(name, globals, locals, fromlist, level)

_rr_safe_builtins = dict(vars(builtins))
for _rr_name in _rr_forbidden_names:
    _rr_safe_builtins.pop(_rr_name, None)
_rr_safe_builtins['__import__'] = _rr_import
_rr_lines = iter(_rr_stdin.splitlines())
_rr_safe_builtins['input'] = lambda prompt='': (print(prompt, end='') or next(_rr_lines))
_rr_out, _rr_err = io.StringIO(), io.StringIO()
_rr_old_out, _rr_old_err = sys.stdout, sys.stderr
_rr_events = 0
def _rr_trace(frame, event, arg):
    global _rr_events
    if event in ('line', 'call'):
        _rr_events += 1
        if _rr_events > 100000:
            raise TimeoutError('Execution budget exceeded; check for an infinite loop.')
    return _rr_trace

_rr_result = {'ok': False, 'stdout': '', 'stderr': '', 'error_type': None, 'error_message': None}
try:
    sys.stdout, sys.stderr = _rr_out, _rr_err
    sys.settrace(_rr_trace)
    exec(compile(_rr_tree, '<student-code>', 'exec'), {'__builtins__': _rr_safe_builtins}, {})
    _rr_result['ok'] = True
except BaseException as exc:
    _rr_result['error_type'] = type(exc).__name__
    _rr_result['error_message'] = str(exc)
    _rr_err.write(''.join(traceback.format_exception_only(type(exc), exc)))
finally:
    sys.settrace(None)
    sys.stdout, sys.stderr = _rr_old_out, _rr_old_err
    _rr_result['stdout'] = _rr_out.getvalue()[-6000:]
    _rr_result['stderr'] = _rr_err.getvalue()[-3000:]
json.dumps(_rr_result, ensure_ascii=False)
`);
    return JSON.parse(String(raw));
  } catch (error) {
    const message = String(error?.message || error).slice(-3000);
    const type = /PermissionError/.test(message)
      ? "PermissionError"
      : /SyntaxError/.test(message)
        ? "SyntaxError"
        : "RuntimeError";
    return { ok: false, stdout: "", stderr: message, error_type: type, error_message: message.split("\n").at(-1) || message };
  }
}

async function rescuePythonSnippet(args) {
  validateSnippetInput(args.original_code, "original_code");
  validateSnippetInput(args.candidate_code, "candidate_code");
  return withPyodideLock(async () => {
    const runtime = await getPyodideRuntime();
    if (runtime.startupError) throw new Error(`Python rescue runtime is unavailable: ${runtime.startupError}`);
    const cases = Array.isArray(args.test_cases) && args.test_cases.length
      ? args.test_cases.slice(0, MAX_SNIPPET_CASES)
      : [{ name: "default", stdin: "" }];
    const results = [];
    for (let index = 0; index < cases.length; index += 1) {
      const test = cases[index] || {};
      const before = await executePythonSnippet(runtime, args.original_code, test.stdin || "");
      const after = await executePythonSnippet(runtime, args.candidate_code, test.stdin || "");
      const expectedProvided = Object.prototype.hasOwnProperty.call(test, "expected_stdout");
      const outputMatches = !expectedProvided || normalizeOutput(after.stdout) === normalizeOutput(test.expected_stdout);
      results.push({
        name: String(test.name || `case-${index + 1}`),
        expected_stdout: expectedProvided ? String(test.expected_stdout) : null,
        before,
        after,
        candidate_passed: after.ok && outputMatches,
        output_matches: outputMatches,
      });
    }
    const beforeFailed = results.some((item) => !item.before.ok || (item.expected_stdout !== null && normalizeOutput(item.before.stdout) !== normalizeOutput(item.expected_stdout)));
    const candidatePassed = results.every((item) => item.candidate_passed);
    const fixVerified = beforeFailed && candidatePassed;
    return {
      ok: true,
      mode: "single_snippet_rescue",
      verification_level: "L1_SNIPPET_EXECUTION",
      status: fixVerified ? "fix_verified" : candidatePassed ? "candidate_runs" : "candidate_failed",
      fix_verified: fixVerified,
      candidate_passed: candidatePassed,
      before_failed: beforeFailed,
      reported_error: String(args.reported_error || "").slice(0, 2000) || null,
      test_results: results,
      user_summary: fixVerified
        ? `修复已真实运行验证：修改前失败，修改后通过 ${results.length} 个用例。`
        : candidatePassed
          ? `候选代码通过 ${results.length} 个运行用例，但未观察到修改前失败，不能宣称已验证修复。`
          : `候选代码仍未通过全部运行用例，请根据错误继续修改。`,
      boundary: "This verifies the supplied snippet and test cases only; it is not a full-project or paper reproduction claim.",
    };
  });
}

async function reproduceWithPyodide(snapshot) {
  let runtime = await getPyodideRuntime();
  if (runtime.startupError) {
    return {
      status: "pyodide_unavailable",
      verified: false,
      repository: snapshot.slug,
      commit_sha: snapshot.commit,
      backend: "pyodide_wasm_allowlist",
      exit_code: null,
      counts: null,
      error: runtime.startupError,
    };
  }
  runtime = await ensurePytestRuntime(runtime);
  if (runtime.startupError) {
    return {
      status: "pytest_runtime_unavailable",
      verified: false,
      repository: snapshot.slug,
      commit_sha: snapshot.commit,
      backend: "pyodide_wasm_allowlist",
      exit_code: null,
      counts: null,
      error: runtime.startupError,
    };
  }
  pyodideLog.length = 0;
  const started = Date.now();
  let exitCode = null;
  let mounted = false;
  try {
    runtime.mountNodeFS("/project", snapshot.project);
    mounted = true;
    exitCode = Number(await runtime.runPythonAsync(`
import os, sys, pytest
os.chdir('/project')
sys.path.insert(0, '/project/src')
result = pytest.main(['-q', '-p', 'no:cacheprovider', 'tests/test_basic.py'])
int(result)
`));
  } catch (error) {
    pyodideLog.push(String(error?.message || error));
  } finally {
    // The Pyodide runtime is reused across MCP calls. Always leave its current
    // directory outside the NodeFS mount, remove stale import paths, and
    // unmount before the temporary checkout is deleted by reproduceProject().
    try {
      await runtime.runPythonAsync(`
import os, sys
os.chdir('/')
sys.path[:] = [p for p in sys.path if not p.startswith('/project')]
`);
    } finally {
      if (mounted) runtime.FS.unmount("/project");
    }
  }
  const output = pyodideLog.join("\n");
  return {
    status: exitCode === 0 ? "verified" : "verification_failed",
    verified: exitCode === 0,
    repository: snapshot.slug,
    commit_sha: snapshot.commit,
    backend: "pyodide_wasm_allowlist",
    verification_command: "pytest -q -p no:cacheprovider tests/test_basic.py",
    exit_code: exitCode,
    timed_out: false,
    duration_seconds: Math.round((Date.now() - started) / 100) / 10,
    counts: extractCounts(output),
    log_tail: output.slice(-10000),
    evidence_note: "A deterministic core smoke suite actually executed in sandboxed CPython WebAssembly because the host did not expose native Python; this is not a claim that the full upstream suite ran.",
  };
}

async function reproduceProject(repoUrl) {
  const snapshot = await cloneRepository(repoUrl);
  try {
    const pythonCandidates = process.platform === "win32" ? ["python"] : ["python3", "python"];
    let python = null;
    for (const candidate of pythonCandidates) {
      const check = run(candidate, ["--version"], { timeout: 5000 });
      if (check.exit_code === 0) { python = candidate; break; }
    }
    if (!python) {
      const fallback = await withPyodideLock(() => reproduceWithPyodide(snapshot));
      return withAttestation(fallback);
    }

    let execution = run(python, ["-m", "pytest", "-q", "--ignore=tests/test_utils/test_echo_via_pager.py"], {
      cwd: snapshot.project,
      timeout: 90000,
      env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1", PYTHONPATH: join(snapshot.project, "src") },
    });
    if (/No module named pytest/.test(execution.stderr)) {
      const site = join(snapshot.root, "site");
      const install = run(python, ["-m", "pip", "install", "--disable-pip-version-check", "--no-input", "--progress-bar", "off", "--target", site, "pytest>=8,<10"], { timeout: 60000 });
      if (install.exit_code !== 0) return { verified: false, repository: snapshot.slug, commit_sha: snapshot.commit, status: "pytest_install_failed", install };
      execution = run(python, ["-m", "pytest", "-q", "--ignore=tests/test_utils/test_echo_via_pager.py"], {
        cwd: snapshot.project,
        timeout: 90000,
        env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1", PYTHONPATH: `${site}${process.platform === "win32" ? ";" : ":"}${join(snapshot.project, "src")}` },
      });
    }
    const output = `${execution.stdout}\n${execution.stderr}`;
    return withAttestation({
      status: execution.exit_code === 0 && !execution.timed_out ? "verified" : "verification_failed",
      verified: execution.exit_code === 0 && !execution.timed_out,
      repository: snapshot.slug,
      commit_sha: snapshot.commit,
      backend: "hosted_direct_allowlist",
      verification_command: execution.command,
      exit_code: execution.exit_code,
      timed_out: execution.timed_out,
      duration_seconds: execution.duration_seconds,
      counts: extractCounts(output),
      log_tail: output.slice(-10000),
      evidence_note: "Verification status is derived only from this allow-listed hosted process exit code.",
    });
  } finally {
    rmSync(snapshot.root, { recursive: true, force: true });
  }
}

function windowsProbe() {
  return {
    ok: true,
    platform: "windows",
    changes_system: false,
    command: "$ErrorActionPreference='Continue'; Write-Output '=== SYSTEM ==='; Get-CimInstance Win32_OperatingSystem | Select-Object Caption,Version,OSArchitecture; Write-Output '=== PYTHON ==='; python --version; Write-Output '=== PIP ==='; python -m pip --version; Write-Output '=== PACKAGES ==='; python -m pip list --format=freeze",
    instructions: "Run this in PowerShell, review it, and paste only the relevant output back. RepoRescue cannot read a user's computer automatically.",
  };
}

async function callTool(name, args) {
  if (name === "rescue_python_snippet") return rescuePythonSnippet(args);
  if (name === "inspect_github_project") return inspectProject(args.repo_url);
  if (name === "reproduce_python_project") return reproduceProject(args.repo_url);
  if (name === "windows_environment_probe") return windowsProbe();
  throw new Error(`Unknown tool: ${name}`);
}

function send(message) {
  const payload = `${JSON.stringify(message)}\n`;
  protocolWrite(payload);
}

const input = createInterface({ input: process.stdin, crlfDelay: Infinity });
input.on("line", async (line) => {
  if (!line.trim()) return;
  let request;
  try { request = JSON.parse(line); } catch { return; }
  if (request.id === undefined || request.id === null) return;
  try {
    let result;
    if (request.method === "initialize") {
      result = { protocolVersion: request.params?.protocolVersion || "2025-03-26", capabilities: { tools: { listChanged: false } }, serverInfo: { name: "repo-rescue-mcp", version: "0.2.0" } };
    } else if (request.method === "ping") {
      result = {};
    } else if (request.method === "tools/list") {
      result = { tools };
    } else if (request.method === "tools/call") {
      const value = await callTool(request.params?.name, request.params?.arguments || {});
      result = { content: [{ type: "text", text: JSON.stringify(value, null, 2) }], isError: false };
    } else {
      send({ jsonrpc: "2.0", id: request.id, error: { code: -32601, message: `Method not found: ${request.method}` } });
      return;
    }
    send({ jsonrpc: "2.0", id: request.id, result });
  } catch (error) {
    send({ jsonrpc: "2.0", id: request.id, result: { content: [{ type: "text", text: JSON.stringify({ ok: false, verified: false, error: String(error?.message || error) }) }], isError: true } });
  }
});
